1. Database Centric Architecture/Blog.Web/Areas/Admin/Controllers/ArticlesController.cs
namespace Blog.Web.Areas.Admin.Controllers
{
    using System.Threading.Tasks;
    using Blog.Controllers;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Services;
    using Services.Models;

    [Area(ControllerConstants.AdministratorArea)]
    [Authorize(Roles = ControllerConstants.AdministratorRole)]
    public class ArticlesController : Controller
    {
        private readonly IArticleService articleService;

        public ArticlesController(IArticleService articleService)
            => this.articleService = articleService;

        public async Task<IActionResult> All()
        {
            var articles = await this.articleService
                .All<ArticleNonPublicListingServiceModel>(pageSize: int.MaxValue, publicOnly: false);

            return this.View(articles);
        }
        
        public async Task<IActionResult> ChangeVisibility(int id)
        {
            await this.articleService.ChangeVisibility(id);
            return this.RedirectToAction(nameof(this.All));
        }
    }
}

1. Database Centric Architecture/Blog.Web/Areas/Admin/Views/Articles/All.cshtml
@model IEnumerable<ArticleNonPublicListingServiceModel>

@{
    ViewData.SetTitle("Articles Administration");
}

<h1 class="display-4 text-center">@ViewData.GetTitle()</h1>

@if (Model.Any())
{
    <table class="table table-bordered">
        <tr>
            <th>
                Title
            </th>
            <th>
                Author
            </th>
            <th>
                Public
            </th>
            <th>
                Publish Date
            </th>
            <th></th>
        </tr>
        @foreach (var article in Model)
        {
            <tr>
                <td>
                    <a asp-area="" asp-controller="Articles" asp-action="Details" asp-route-id="@article.Id">@article.Title</a>
                </td>
                <td>@article.Author</td>
                <td>@(article.IsPublic ? "Yes" : "No")</td>
                <td>@article.PublishedOn?.ToShortDateString()</td>
                <td>
                    <a asp-area="" asp-controller="Articles" asp-action="Edit" asp-route-id="@article.Id" class="btn btn-warning">Edit</a>
                    <a asp-area="" asp-controller="Articles" asp-action="Delete" asp-route-id="@article.Id" class="btn btn-danger">Delete</a>

                    @{
                        var visibilityButtonClass = article.IsPublic ? "btn-dark" : "btn-primary";
                        var visibilityButtonText = article.IsPublic ? "Hide" : "Make Public";
                    }

                    <a asp-area="Admin" asp-controller="Articles" asp-action="ChangeVisibility" asp-route-id="@article.Id" class="btn @visibilityButtonClass">@visibilityButtonText</a>
                </td>
            </tr>
        }
    </table>
}
else
{
    <h2 class="text-center margin-top-20">No articles available in the system!</h2>
}

1. Database Centric Architecture/Blog.Web/Views/Articles/All.cshtml
@model ArticleListingViewModel

@{
    ViewData.SetTitle("All Articles");
}

@if (Model.Articles.Any())
{
    <div class="text-center">
        <h1 class="display-4">@ViewData.GetTitle()</h1>
        <partial name="_ArticleListingPartial" model="@Model.Articles" />

        <div class="container margin-top-20">
            <div class="row">
                <div class="col-2">
                    @if (Model.Page > 1)
                    {
                        <a class="disabled" href="/Articles/All?page=@(Model.Page - 1)">&lt;&lt; Prev</a>
                    }
                </div>
                <div class="col-md-8"></div>
                <div class="col-2">
                    @if (Model.Total - ServicesConstants.ArticlesPerPage * Model.Page > 0)
                    {
                        <a class="pull-right" href="/Articles/All?page=@(Model.Page + 1)">Next &gt;&gt;</a>
                    }
                </div>
            </div>
        </div>
    </div>
}
else
{
    <h2 class="text-center margin-top-20">No articles available here!</h2>
}

1. Database Centric Architecture/Blog.Web/Views/Articles/Create.cshtml
@model ArticleFormModel

@{
    ViewData.SetTitle("Create Article");
}

<h2>Create Article</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <partial name="_ArticleForm" model="@Model" />
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

1. Database Centric Architecture/Blog.Web/Views/Articles/Delete.cshtml
@model int

@{
    ViewData.SetTitle("Delete Article");
}

<h1>Are you sure you want do delete this article?</h1>

<a class="btn btn-danger" asp-controller="Articles" asp-action="ConfirmDelete" asp-route-id="@Model">Yes</a>
<a class="btn btn-default" asp-controller="Articles" asp-action="Details" asp-route-id="@Model">No</a>

1. Database Centric Architecture/Blog.Web/Views/Articles/Details.cshtml
@model ArticleDetailsServiceModel

@{
    ViewData.SetTitle(Model.Title);
}

<h2>@Html.DisplayFor(model => model.Title) @(Model.IsPublic ? string.Empty : "(Unpublished)")</h2>

@if (User.Identity.Name == Model.Author)
{
    <div>
        <a class="btn btn-warning" asp-area="" asp-controller="Articles" asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
        <a class="btn btn-danger" asp-area="" asp-controller="Articles" asp-action="Delete" asp-route-id="@Model.Id">Delete</a>
    </div>
    <br />
}

<div>
    <h5>
        @Model.PublishedOn?.ToShortDateString() by @Html.DisplayFor(model => model.Author)
    </h5>
    <hr />
    <dl class="row">
        <dd class="col-sm-8">
            @Html.DisplayFor(model => model.Content)
        </dd>
    </dl>
</div>

1. Database Centric Architecture/Blog.Web/Views/Articles/Edit.cshtml
@model ArticleFormModel

@{
    ViewData.SetTitle("Edit Article");
}

<h2>Edit Article</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <partial name="_ArticleForm" model="@Model" />
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

1. Database Centric Architecture/Blog.Web/Views/Articles/Mine.cshtml
@model IEnumerable<ArticleForUserListingServiceModel>

@{
    ViewData.SetTitle("My Articles");
}

@{
    var publishedArticles = Model
        .Where(a => a.IsPublic)
        .OrderByDescending(a => a.PublishedOn)
        .ToList();

    var waitingForApprovalArticles = Model
        .Where(a => !a.IsPublic)
        .OrderByDescending(a => a.PublishedOn)
        .ToList();
}

@if (!publishedArticles.Any() && !waitingForApprovalArticles.Any())
{
    <h2 class="text-center margin-top-20">You don't have any articles yet! Create one from <a asp-controller="Articles" asp-action="Create">here</a>!</h2>
}

@if (publishedArticles.Any())
{
    <div class="text-center">
        <h1 class="display-4">Published Articles</h1>
        <partial name="_ArticleListingPartial" model="@publishedArticles" />
    </div>
}

@if (waitingForApprovalArticles.Any())
{
    <div class="text-center">
        <h1 class="display-4">Waiting For Approval</h1>
        <partial name="_ArticleListingPartial" model="@waitingForApprovalArticles" />
    </div>
}

1. Database Centric Architecture/Blog.Web/Views/Articles/_ArticleForm.cshtml
@model ArticleFormModel

<form method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Title" class="control-label"></label>
        <input asp-for="Title" class="form-control" />
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Content" class="control-label"></label>
        <textarea asp-for="Content" rows="15" class="form-control"></textarea>
        <span asp-validation-for="Content" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-primary" />
    </div>
</form>

1. Database Centric Architecture/Blog.Web/Views/Home/Index.cshtml
@model IEnumerable<ArticleListingServiceModel>
@{
    ViewData.SetTitle("Home Page");
}

<div class="text-center jumbotron margin-top-20">
    <h1 class="display-4">Welcome to our Blog</h1>
</div>

<partial name="_ArticleListingPartial" model="@Model"/>

1. Database Centric Architecture/Blog.Web/Views/Shared/_ArticleListingPartial.cshtml
@model IEnumerable<ArticleListingServiceModel>

<div class="container">
    <div class="row">
        @foreach (var article in Model)
        {
            <div class="col-4">
                <div class="panel article-panel">
                    <div class="panel-heading">
                        <h3 class="text-center">
                            <a class="text-dark" asp-area="" asp-controller="Articles" asp-action="Details" asp-route-id="@article.Id">@article.Title</a>
                        </h3>
                    </div>
                    <div class="panel-body text-center">
                        @(article.PublishedOn != null ? article.PublishedOn.Value.ToShortDateString() : string.Empty) <em>by @article.Author</em>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

1. Database Centric Architecture/Blog.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Blog</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Blog</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Articles" asp-action="All">Articles</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Articles" asp-action="Create">Create</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @if (TempData.ContainsKey(ControllerConstants.SuccessMessage))
            {
                <div class="alert alert-success" role="alert">
                    @TempData[ControllerConstants.SuccessMessage]
                </div>
            }
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2018 - Blog.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>